version: '3'

services:
    db:
        image: postgres:12
        container_name: db
        environment:
            POSTGRES_USER: andrii
            POSTGRES_DB: sammy
            POSTGRES_PASSWORD: 1234
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data/
    api:
        build: DevelopsTodayTest
        volumes:
            - ./DevelopsTodayTest:/api
        command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
  db-data: