version: '3'

services:
    db:
        image: postgres:12
        container_name: db
        environment:
            POSTGRES_USER: andrii
            POSTGRES_DB: sammy
            POSTGRES_PASSWORD: 1234
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data/
    api:
        build: .
        volumes:
            - ./DevelopsTodayTest:/api
        command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db
    rabbitmq:
        hostname: rabbitmq
        image: "rabbitmq"
        container_name: rabbitmq
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq/data
        ports:
            - 5672:5672
    celery:
        build: .
        container_name: celery_worker
        command: bash -c "celery -A DevelopsTodayTest worker -l info"
        volumes:
            - ./DevelopsTodayTest:/api
        depends_on:
            - db
            - rabbitmq
    celery-beat:
        build: .
        container_name: celery_beat
        command: bash -c "celery -A DevelopsTodayTest beat -l info"
        volumes:
            - ./DevelopsTodayTest:/api
        depends_on:
            - celery
volumes:
  db-data: